// A content-keyed cache of dense matcher output, as a roma::Matcher decorator:
// it stores what the wrapped matcher returned and touches no model code. The
// key is a SHA-256 over both images' pixels and sizes, the matcher identity and
// its input size, never a name or a file time. Entries hold the warp, the
// certainty and the precision as float32, so a hit is the matcher's output to the bit
// (docs/notes/densify.md, "Warp cache").
#pragma once

#include <array>
#include <cstdint>
#include <functional>
#include <map>
#include <mutex>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

#include "roma/Matcher.h"

namespace roma {

// A new Warp field must be stored too, and old entries must then miss.
static_assert(sizeof(Warp) == 2 * sizeof(int) + 3 * sizeof(std::vector<float>),
              "Warp gained a field: store it in WarpCache.cpp's entry format and raise kEntryVersion");

inline constexpr uint32_t kEntryVersion = 2;   // 2: precision after the certainty
inline constexpr uint64_t kDefaultCacheBudget = 16ull << 30;

// "16G", "500MiB", "1.5GB", "123": K, M, G, T are binary whatever the spelling.
// False on anything else, zero included.
bool parseByteSize(const std::string& text, uint64_t* out);
std::string formatByteSize(uint64_t bytes);

// ---- identity -------------------------------------------------------------

// Everything on the RoMa v2 path that can change a warp, as resolved. Every
// field must reach the identity; warp_cache_test varies each in turn.
struct RomaSettings {
    std::string preset;               // "base", "high", ...
    int lr = 0, hr = 0;               // the preset's resolutions
    std::string checkpoint_sha256;    // of the bytes that were loaded
    bool f16_weights = false;         // roma::f16_weights(): coop matrices decide it
    bool rope_rounds = true;          // roma::matcher_rope_rounds()
    bool local_corr_fused = true;     // roma::local_corr_fused()
    std::string gemm_kernel;          // SS_NN_GEMM_KERNEL as set, "" unset
    std::string device;               // the selector of the device that ran it
    std::string model_digest;         // modelSourceDigest()
};
std::string romaIdentity(const RomaSettings& s);

// SHA-256 over the sources that make the warp (src/roma/model, shaders, src/nn),
// regenerated by the build whenever one of them changes.
const char* modelSourceDigest();

// ---- storage --------------------------------------------------------------

struct WarpCacheOptions {
    std::string dir;                              // created if missing
    uint64_t budget_bytes = kDefaultCacheBudget;  // least recently used entries go first
};

struct WarpCacheInfo {
    uint64_t entries = 0, bytes = 0;
    uint64_t evicted = 0, evicted_bytes = 0;      // this process
    uint64_t written = 0, written_bytes = 0;      // this process
};

struct ClearResult {
    uint64_t entries = 0, bytes = 0;
};

enum class Lookup { Hit, Miss, Corrupt };

class WarpCache {
public:
    // Throws std::runtime_error when the directory cannot be made or read.
    explicit WarpCache(const WarpCacheOptions& opt);

    // A hit fills `out` and `seconds` (the matcher's time when the entry was
    // made). An entry that does not verify is removed and reported Corrupt.
    Lookup get(const std::string& key, Warp* out, double* seconds);
    // False when it could not be written (nothing partial is left) or the warp
    // is not finite.
    bool put(const std::string& key, const Warp& w, double seconds);
    // Entries and abandoned temporaries only; any other file stays.
    ClearResult clear();

    WarpCacheInfo info() const;
    const std::string& dir() const { return dir_; }
    uint64_t budget() const { return budget_; }
    std::string entryPath(const std::string& key) const;

private:
    struct Slot { uint64_t bytes = 0, use = 0; };
    void scan();
    void touch(const std::string& key, uint64_t bytes);
    void evictLocked(const std::string& keep);

    std::string dir_;
    uint64_t budget_;
    mutable std::mutex mu_;
    std::unordered_map<std::string, Slot> slots_;
    std::map<uint64_t, std::string> by_use_;
    uint64_t clock_ = 0, bytes_ = 0;
    WarpCacheInfo info_;
};

// Exposed so a test can hand the decoder a damaged or hostile entry.
uint64_t entryChecksum(const uint8_t* p, size_t n);
std::vector<uint8_t> encodeEntry(const std::string& key, const Warp& w, double seconds);
bool decodeEntry(const std::vector<uint8_t>& bytes, const std::string& key, Warp* out,
                 double* seconds, std::string* why);

// ---- the decorator --------------------------------------------------------

struct CachedStats {
    int64_t hits = 0, misses = 0;
    int64_t corrupt = 0;        // failed to verify; matched again
    int64_t uncacheable = 0;    // not finite, or an image that was empty
    int64_t write_failed = 0;
    double seconds_matched = 0;   // matcher time on misses
    double seconds_loaded = 0;    // keying, reading and verifying hits
    double seconds_overhead = 0;  // keying and writing on misses
    double seconds_saved = 0;     // hits' recorded matcher time, less seconds_loaded
};

class CachedMatcher : public Matcher {
public:
    // `identity` names everything about `inner` that changes its output; an
    // empty one throws, since nothing would then keep a stale entry out.
    CachedMatcher(Matcher& inner, WarpCache& cache, std::string identity);
    int inputSize() const override { return inner_.inputSize(); }
    Warp match(const MatchImage& a, const MatchImage& b) override;
    // A -> B and B -> A, each its own entry: `both` runs only when neither is
    // stored, and a single match() fills the one that is missing.
    std::pair<Warp, Warp> matchBoth(const MatchImage& a, const MatchImage& b,
                                    const std::function<std::pair<Warp, Warp>(const MatchImage&, const MatchImage&)>& both);
    std::string describe() const override { return inner_.describe(); }

    const CachedStats& stats() const { return stats_; }
    std::string keyFor(const MatchImage& a, const MatchImage& b) const;

private:
    Matcher& inner_;
    WarpCache& cache_;
    std::string identity_;
    CachedStats stats_;
};

}  // namespace roma
