#!/usr/bin/env python3
"""LICENSES/*  ->  the .cpp files that embed each licence text, so the consent
dialog and the CLI can show a licence in full with no file to find at run time.
The output is committed.

    python3 tools/gen_license_texts.py           rewrite them
    python3 tools/gen_license_texts.py --check   exit 1 if any is stale
"""
import pathlib
import sys

root = pathlib.Path(__file__).resolve().parent.parent
# (output, header it includes, namespace, [(symbol, LICENSES/ file)])
OUTPUTS = [
    ("src/core/LicenseTexts.cpp", "core/LicenseTexts.h", "spirula::license", [
        ("kSam3License", "LICENSES/SAM3-License.txt"),
        ("kSam2Apache", "LICENSES/Apache-2.0-SAM2.txt"),
        ("kGdinoApache", "LICENSES/Apache-2.0-GroundingDINO.txt"),
        ("kBirefnetMit", "LICENSES/MIT-BiRefNet.txt"),
        ("kRomaMit", "LICENSES/MIT-RoMaV2.txt"),
        ("kDinov3License", "LICENSES/DINOv3-License.txt"),
    ]),
]


def render(include, namespace, sources):
    out = ["// GENERATED by tools/gen_license_texts.py from LICENSES/ -- do not edit.",
           f'#include "{include}"', "", f"namespace {namespace} {{", ""]
    for sym, rel in sources:
        text = (root / rel).read_text(encoding="utf-8")
        assert ")LIC\"" not in text
        # MSVC rejects a literal piece over 16 KB; pieces of whole lines stay far under.
        pieces, cur = [], ""
        for line in text.splitlines(keepends=True):
            if len(cur.encode()) + len(line.encode()) > 8000:
                pieces.append(cur)
                cur = ""
            cur += line
        pieces.append(cur)
        out.append(f"// {rel}")
        out.append(f"const char* const {sym} =")
        out += [f'R"LIC({p})LIC"' for p in pieces]
        out[-1] += ";"
        out.append("")
    out.append(f"}}  // namespace {namespace}")
    return "\n".join(out) + "\n"


stale = False
for dst_rel, include, namespace, sources in OUTPUTS:
    body = render(include, namespace, sources)
    dst = root / dst_rel
    if "--check" in sys.argv:
        stale |= not (dst.exists() and dst.read_text(encoding="utf-8") == body)
    else:
        dst.write_text(body, encoding="utf-8")
sys.exit(1 if stale else 0)
