#!/usr/bin/env python3
"""LICENSES/*  ->  src/core/LicenseTexts.cpp, so the consent dialog and the CLI can
show a licence in full with no file to find at run time. The output is committed.

    python3 tools/gen_license_texts.py           rewrite it
    python3 tools/gen_license_texts.py --check   exit 1 if it is stale
"""
import pathlib
import sys

root = pathlib.Path(__file__).resolve().parent.parent
SOURCES = [
    ("kDinov3Agreement", "LICENSES/DINOv3-License-Agreement.md"),
    ("kRomaV2Mit", "LICENSES/MIT-RoMaV2.txt"),
]

out = ["// GENERATED by tools/gen_license_texts.py from LICENSES/ -- do not edit.",
       '#include "core/LicenseTexts.h"', "", "namespace spirula::license {", ""]
for sym, rel in SOURCES:
    text = (root / rel).read_text(encoding="utf-8")
    assert ")LIC\"" not in text
    # MSVC rejects a literal piece over 16 KB; pieces of whole lines stay far under.
    pieces, cur = [], ""
    for line in text.splitlines(keepends=True):
        if len(cur.encode()) + len(line.encode()) > 8000:
            pieces.append(cur)
            cur = ""
        cur += line
    pieces.append(cur)
    out.append(f"// {rel}")
    out.append(f"const char* const {sym} =")
    out += [f'R"LIC({p})LIC"' for p in pieces]
    out[-1] += ";"
    out.append("")
out.append("}  // namespace spirula::license")
body = "\n".join(out) + "\n"
dst = root / "src/core/LicenseTexts.cpp"
if "--check" in sys.argv:
    sys.exit(0 if dst.exists() and dst.read_text(encoding="utf-8") == body else 1)
dst.write_text(body, encoding="utf-8")
